PREFIX cacao: <http://w3id.org/cacao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT DISTINCT ?physicalArtefact ?digitalArtefact WHERE {
  ?physicalArtefact a cacao:CACAO_0000023 ;
                    crm:P138i_has_representation ?digitalArtefact .
  ?digitalArtefact a cacao:CACAO_0000003 .
}
LIMIT 20
