PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT DISTINCT ?artefact ?location WHERE {
  { ?artefact crm:P55_has_current_location ?location }
  UNION
  { ?artefact crm:P53_has_former_or_current_location ?location }
}
LIMIT 20
