PREFIX odrl: <http://www.w3.org/ns/odrl/2/>

SELECT DISTINCT ?policy ?permission ?leftOperand ?operator ?rightOperand WHERE {
  ?policy odrl:permission ?permission .
  ?permission odrl:constraint ?constraint .
  ?constraint odrl:leftOperand ?leftOperand ;
              odrl:operator ?operator ;
              odrl:rightOperand ?rightOperand .
}
LIMIT 20
