PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT DISTINCT ?artefact ?right ?holder WHERE {
  ?artefact crm:P104_is_subject_to ?right .
  {
    ?right crm:P105_right_held_by ?holder .
  }
  UNION
  {
    ?right crm:P75_is_possessed_by ?holder .
  }
}
LIMIT 20
